spring:
    application:
        name: podo-arrival

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}

    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                default_batch_fetch_size: 500
                format_sql: true

    jackson:
        serialization:
            fail-on-empty-beans: false

secret:
    jwt: ${SECRET_JWT}
    redis-url: ${REDIS_URL}
